.github/ISSUE_TEMPLATE/upstream_request.ymlname: ⬆️ Запрос на подтягивание новых стратегий
description: "Если хотите, чтобы новые стратегии из upstream Flowseal были интегрированы."
title: "[UPSTREAM] "
labels: ["upstream", "feature request"]
assignees: []

body:
  - type: markdown
    content: |
      Этот issue предназначен для запросов на интеграцию новых стратегий из upstream Flowseal.

  - type: checkboxes
    id: checklist
    attributes:
      label: "Проверено перед созданием запроса"
      options:
        - label: "Я не прошу исправить баги в текущем скрипте этим issue"

  - type: textarea
    id: reason
    attributes:
      label: "Комментарий"
      placeholder: "Например, нужна для обхода новых ограничений на YouTube"
