// Code generated by twirp-protoc-gen-twirp v8.1.2, DO NOT EDIT.
// source: rpc/zapret-daemon/service.proto

package twirp

import (
	"context"

	"github.com/twitchtv/twirp"
)

// ZapretServiceServer is the server API for ZapretService service.
type ZapretServiceServer interface {
	GetStrategyList(context.Context, *GetStrategyListRequest) (*GetStrategyListResponse, error)
	RunSelectedStrategy(context.Context, *RunSelectedStrategyRequest) (*RunSelectedStrategyResponse, error)
	StopStrategy(context.Context, *StopStrategyRequest) (*StopStrategyResponse, error)
	InstallZapret(context.Context, *InstallZapretRequest) (*InstallZapretResponse, error)
	GetAvailableVersions(context.Context, *GetAvailableVersionsRequest) (*GetAvailableVersionsResponse, error)
	GetActiveNFTRules(context.Context, *GetActiveNFTRulesRequest) (*GetActiveNFTRulesResponse, error)
	GetActiveProcesses(context.Context, *GetActiveProcessesRequest) (*GetActiveProcessesResponse, error)
	RestartDaemon(context.Context, *RestartDaemonRequest) (*RestartDaemonResponse, error)
}

// server implements ZapretServiceServer.
type server struct {
	service ZapretService
}

// NewZapretServiceServer creates a ZapretService server.
func NewZapretServiceServer(service ZapretService, hooks twirp.ServerHooks) *server {
	return &server{service: service}
}

// GetStrategyList implements ZapretServiceServer.
func (s *server) GetStrategyList(ctx context.Context, req *GetStrategyListRequest) (*GetStrategyListResponse, error) {
	return s.service.GetStrategyList(ctx, req)
}

// RunSelectedStrategy implements ZapretServiceServer.
func (s *server) RunSelectedStrategy(ctx context.Context, req *RunSelectedStrategyRequest) (*RunSelectedStrategyResponse, error) {
	return s.service.RunSelectedStrategy(ctx, req)
}

// StopStrategy implements ZapretServiceServer.
func (s *server) StopStrategy(ctx context.Context, req *StopStrategyRequest) (*StopStrategyResponse, error) {
	return s.service.StopStrategy(ctx, req)
}

// InstallZapret implements ZapretServiceServer.
func (s *server) InstallZapret(ctx context.Context, req *InstallZapretRequest) (*InstallZapretResponse, error) {
	return s.service.InstallZapret(ctx, req)
}

// GetAvailableVersions implements ZapretServiceServer.
func (s *server) GetAvailableVersions(ctx context.Context, req *GetAvailableVersionsRequest) (*GetAvailableVersionsResponse, error) {
	return s.service.GetAvailableVersions(ctx, req)
}

// GetActiveNFTRules implements ZapretServiceServer.
func (s *server) GetActiveNFTRules(ctx context.Context, req *GetActiveNFTRulesRequest) (*GetActiveNFTRulesResponse, error) {
	return s.service.GetActiveNFTRules(ctx, req)
}

// GetActiveProcesses implements ZapretServiceServer.
func (s *server) GetActiveProcesses(ctx context.Context, req *GetActiveProcessesRequest) (*GetActiveProcessesResponse, error) {
	return s.service.GetActiveProcesses(ctx, req)
}

// RestartDaemon implements ZapretServiceServer.
func (s *server) RestartDaemon(ctx context.Context, req *RestartDaemonRequest) (*RestartDaemonResponse, error) {
	return s.service.RestartDaemon(ctx, req)
}

// MethodName returns the name of the service method.
func (s *server) MethodName() string {
	return "ZapretService"
}

// ServiceName returns the full service name.
func (s *server) ServiceName() string {
	return "zapret.twirp.ZapretService"
}

// PathPrefix returns the path prefix for this service.
func (s *server) PathPrefix() string {
	return "/twirp/zapret.twirp.ZapretService/"
}